"""Phase 5 — assemble a URDF from Phase 2+3+4 outputs.

Inputs:
  - per_link_meshes:  dict[int -> Trimesh]         (visual geometry)
  - per_link_collisions: dict[int -> Trimesh]      (collision geometry; can be
                                                    the same as visual for MVP)
  - joints:           list[JointEstimate]          (Phase 3)
  - inertials:        dict[int -> LinkInertial]    (Phase 4)
  - template:         Template                     (Phase 4)
  - body_transforms:  list[list[np.ndarray]]       (Phase 2, pose-0 frames)
  - link_names:       optional list[str]           (if user provided names)

Outputs:
  - robot.urdf
  - meshes/linkN.stl (visual)
  - meshes/linkN_collision.stl
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import trimesh
from jinja2 import Template as JinjaTemplate

from mesh2robot.core.joint_extraction import JointEstimate
from mesh2robot.core.physics import LinkInertial
from mesh2robot.core.physics_defaults import Template


URDF_TEMPLATE = JinjaTemplate(
    """<?xml version="1.0"?>
<!-- Generated by mesh2robot. Template basis: {{ template_name }} -->
<robot name="{{ robot_name }}">
{% for link in links %}
  <link name="{{ link.name }}">
    <visual>
      <origin xyz="{{ link.visual_origin }}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{{ link.visual_mesh }}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="{{ link.collision_origin }}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{{ link.collision_mesh }}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="{{ link.com }}" rpy="0 0 0"/>
      <mass value="{{ '%.6f'|format(link.mass) }}"/>
      <inertia ixx="{{ '%.6e'|format(link.ixx) }}" ixy="{{ '%.6e'|format(link.ixy) }}" ixz="{{ '%.6e'|format(link.ixz) }}"
               iyy="{{ '%.6e'|format(link.iyy) }}" iyz="{{ '%.6e'|format(link.iyz) }}"
               izz="{{ '%.6e'|format(link.izz) }}"/>
    </inertial>
  </link>
{% endfor %}
{% for joint in joints %}
  <joint name="{{ joint.name }}" type="{{ joint.type }}">
    <parent link="{{ joint.parent }}"/>
    <child link="{{ joint.child }}"/>
    <origin xyz="{{ joint.origin }}" rpy="{{ joint.rpy }}"/>
    <axis xyz="{{ joint.axis }}"/>
{% if joint.type != 'fixed' %}
    <limit lower="{{ '%.6f'|format(joint.lower) }}" upper="{{ '%.6f'|format(joint.upper) }}" effort="{{ '%.3f'|format(joint.effort) }}" velocity="{{ '%.3f'|format(joint.velocity) }}"/>
    <dynamics damping="{{ '%.4f'|format(joint.damping) }}" friction="{{ '%.4f'|format(joint.friction) }}"/>
{% endif %}
  </joint>
{% endfor %}
</robot>
"""
)


@dataclass
class AssemblyInput:
    robot_name: str
    per_link_meshes: dict[int, trimesh.Trimesh]
    per_link_collisions: dict[int, trimesh.Trimesh]
    joints: list[JointEstimate]
    inertials: dict[int, LinkInertial]
    template: Template
    body_transforms_pose0: list[np.ndarray]     # world->body at pose 0, per body idx
    link_name_map: dict[int, str] | None = None
    # Per-joint (lower, upper) in radians, in CHAIN order. When provided,
    # these win over template and observed-motion limits. Used by the
    # joint_limits resolver to inject collision-aware or user-supplied limits.
    final_limits_per_joint: list[tuple[float, float]] | None = None


def _xyz(v: np.ndarray) -> str:
    return f"{v[0]:.6f} {v[1]:.6f} {v[2]:.6f}"


def _axis_to_rpy(axis_world: np.ndarray, rest_axis: np.ndarray = np.array([0, 0, 1.0])) -> np.ndarray:
    """Compute rpy that rotates rest_axis into axis_world."""
    a = rest_axis / np.linalg.norm(rest_axis)
    b = axis_world / np.linalg.norm(axis_world)
    dot = float(np.clip(a @ b, -1.0, 1.0))
    if dot > 0.9999:
        return np.zeros(3)
    if dot < -0.9999:
        # 180 deg flip around any orthogonal axis
        return np.array([np.pi, 0.0, 0.0])
    axis = np.cross(a, b)
    axis /= np.linalg.norm(axis)
    angle = np.arccos(dot)
    # Rodrigues -> rotation matrix, then to XYZ Euler (rpy order: roll pitch yaw)
    K = np.array([[0, -axis[2], axis[1]],
                  [axis[2], 0, -axis[0]],
                  [-axis[1], axis[0], 0]])
    R = np.eye(3) + np.sin(angle) * K + (1 - np.cos(angle)) * (K @ K)
    return _rotation_to_rpy(R)


def _rotation_to_rpy(R: np.ndarray) -> np.ndarray:
    """3x3 rotation -> (roll, pitch, yaw) URDF convention (Z*Y*X intrinsic)."""
    # Standard XYZ-Euler extraction
    sy = np.sqrt(R[0, 0] ** 2 + R[1, 0] ** 2)
    if sy > 1e-6:
        roll = np.arctan2(R[2, 1], R[2, 2])
        pitch = np.arctan2(-R[2, 0], sy)
        yaw = np.arctan2(R[1, 0], R[0, 0])
    else:
        roll = np.arctan2(-R[1, 2], R[1, 1])
        pitch = np.arctan2(-R[2, 0], sy)
        yaw = 0.0
    return np.array([roll, pitch, yaw])


def _compute_body_world_frames(
    n_bodies: int,
    joints: list[JointEstimate],
    root_body: int,
) -> list[np.ndarray]:
    """Compute each body's world-frame pose at rest (URDF home pose).

    URDF convention: each child link's frame origin coincides with its joint's
    origin at rest. Walk the joint tree from the root and accumulate.

    Given:
      - joints[i].origin is the joint pivot in WORLD frame at rest (Phase 3)
    Produces:
      - T_body[b] = transform from WORLD to body's local frame at rest
    """
    T = [None] * n_bodies
    T[root_body] = np.eye(4)

    # Build adjacency: parent -> [joint, ...]
    out_edges: dict[int, list[JointEstimate]] = {}
    for j in joints:
        out_edges.setdefault(j.parent_body, []).append(j)

    queue = [root_body]
    while queue:
        p = queue.pop(0)
        for j in out_edges.get(p, []):
            if T[j.child_body] is not None:
                continue
            # Child frame origin = joint.origin (world), same orientation as parent.
            # (Joints here are revolute; at rest angle = 0, so rotation component is identity.)
            T_child = T[p].copy()
            T_child[:3, 3] = j.origin
            T[j.child_body] = T_child
            queue.append(j.child_body)

    # Any bodies we couldn't reach (disconnected) get identity — they'll be
    # treated as free-floating and the caller will surface them.
    for b in range(n_bodies):
        if T[b] is None:
            T[b] = np.eye(4)
    return T


def _chain_order(
    body_ids: list[int],
    joints: list[JointEstimate],
    root: int,
) -> tuple[list[int], list[JointEstimate]]:
    """BFS traversal of the kinematic chain from root.

    Returns:
      ordered_bodies: root first, then children in BFS order
      ordered_joints: the joint that CREATES each non-root body, in the same
                      order (so ordered_joints[i] produces ordered_bodies[i+1])
    """
    out_edges: dict[int, list[JointEstimate]] = {}
    for j in joints:
        out_edges.setdefault(j.parent_body, []).append(j)

    ordered_bodies = [root]
    ordered_joints: list[JointEstimate] = []
    seen = {root}
    queue = [root]
    while queue:
        p = queue.pop(0)
        for j in out_edges.get(p, []):
            if j.child_body in seen:
                continue
            seen.add(j.child_body)
            ordered_bodies.append(j.child_body)
            ordered_joints.append(j)
            queue.append(j.child_body)
    # Append any orphaned bodies at the end so nothing is silently dropped
    for b in body_ids:
        if b not in seen:
            ordered_bodies.append(b)
    return ordered_bodies, ordered_joints


def assemble(inp: AssemblyInput, output_dir: Path) -> Path:
    """Write out robot.urdf + meshes/. Returns the URDF path."""
    output_dir = Path(output_dir)
    meshes_dir = output_dir / "meshes"
    meshes_dir.mkdir(parents=True, exist_ok=True)

    all_body_ids = sorted(set(inp.per_link_meshes.keys()))

    # Identify root (body not a child of any joint)
    children = {j.child_body for j in inp.joints}
    roots = [b for b in all_body_ids if b not in children]
    if not roots:
        raise ValueError("No root body found — joint graph has a cycle?")
    root = roots[0]

    # Walk the chain from root so we can emit links + joints in kinematic order.
    ordered_bodies, ordered_joints = _chain_order(all_body_ids, inp.joints, root)

    # Auto-name links as {link_base, link1, link2, ...} in chain order when no
    # user-provided name map. Also re-map user-provided names so output order
    # matches chain order regardless of input dict ordering.
    if inp.link_name_map:
        def name_of(body_id: int) -> str:
            return inp.link_name_map.get(body_id, f"link_{body_id}")
    else:
        auto_names = {ordered_bodies[0]: "link_base"}
        for i, b in enumerate(ordered_bodies[1:], start=1):
            auto_names[b] = f"link{i}"

        def name_of(body_id: int) -> str:
            return auto_names.get(body_id, f"link_{body_id}")

    # Actual world-frame pose of each body at rest.
    n_bodies = max(all_body_ids) + 1 if all_body_ids else 0
    body_T_world = _compute_body_world_frames(n_bodies, inp.joints, root)

    # Export meshes (in the body's local frame, meaning we have to undo the
    # pose-0 world placement so the visual sits at the link origin).
    link_records = []
    for b in ordered_bodies:
        if b not in inp.per_link_meshes:
            continue
        mesh = inp.per_link_meshes[b].copy()
        col = inp.per_link_collisions.get(b, mesh).copy()

        T_world = body_T_world[b]
        T_local = np.linalg.inv(T_world)
        mesh.apply_transform(T_local)
        col.apply_transform(T_local)

        name = name_of(b)
        v_path = meshes_dir / f"{name}.stl"
        c_path = meshes_dir / f"{name}_collision.stl"
        mesh.export(v_path)
        col.export(c_path)

        inertial = inp.inertials.get(b)
        if inertial is None:
            # Fallback: unit mass, identity inertia — should only hit if physics
            # failed for this link (we still want a loadable URDF).
            mass = 0.01
            com = np.zeros(3)
            I = np.eye(3) * 1e-6
        else:
            mass = inertial.mass
            # Transform COM to local frame
            com = (T_local @ np.array([*inertial.com, 1.0]))[:3]
            # Inertia tensor transforms by R I R^T
            R = T_local[:3, :3]
            I = R @ inertial.inertia @ R.T

        link_records.append({
            "name": name,
            "visual_mesh": f"meshes/{name}.stl",
            "collision_mesh": f"meshes/{name}_collision.stl",
            "visual_origin": _xyz(np.zeros(3)),
            "collision_origin": _xyz(np.zeros(3)),
            "com": _xyz(com),
            "mass": mass,
            "ixx": float(I[0, 0]), "iyy": float(I[1, 1]), "izz": float(I[2, 2]),
            "ixy": float(I[0, 1]), "ixz": float(I[0, 2]), "iyz": float(I[1, 2]),
        })

    # Build joint records — each JointEstimate gives us axis/origin in WORLD frame
    # at pose 0. We need origin relative to the PARENT link frame, and axis in
    # the CHILD's local frame (URDF convention).
    # Emit joints in chain order so joint_1 = root->first-child, joint_2 = next, etc.
    joint_records = []
    for i, je in enumerate(ordered_joints):
        parent_name = name_of(je.parent_body)
        child_name = name_of(je.child_body)

        T_parent0 = body_T_world[je.parent_body]
        # Joint origin in parent frame
        origin_w = np.array([*je.origin, 1.0])
        origin_p = (np.linalg.inv(T_parent0) @ origin_w)[:3]
        # Axis in parent frame (we can equivalently express in child frame
        # since joint rotates about this axis; URDF reads axis in CHILD frame,
        # but at rest the two frames share the axis direction).
        R_p = T_parent0[:3, :3]
        axis_p = R_p.T @ je.axis
        axis_p /= np.linalg.norm(axis_p)

        rpy = _axis_to_rpy(axis_p)     # embed the axis in the joint's origin rotation
        eff = (inp.template.effort_per_joint[i]
               if i < len(inp.template.effort_per_joint)
               else 100.0)
        vel = (inp.template.velocity_per_joint[i]
               if i < len(inp.template.velocity_per_joint)
               else 3.14)

        # Joint limits: prefer caller-resolved `final_limits_per_joint` (from
        # the joint_limits resolver — user overrides + collision sweep +
        # template), then template, then observed-motion range * margin.
        final_lims = inp.final_limits_per_joint
        tpl_lims = inp.template.limits_per_joint
        if final_lims is not None and i < len(final_lims):
            lower, upper = final_lims[i]
        elif i < len(tpl_lims) and np.isfinite(tpl_lims[i][0]):
            lower, upper = tpl_lims[i]
        else:
            mid = 0.5 * (je.lower + je.upper)
            half = 0.5 * (je.upper - je.lower) * 4.0
            lower, upper = mid - half, mid + half

        joint_records.append({
            "name": f"joint_{i+1}",
            "type": je.type,
            "parent": parent_name,
            "child": child_name,
            "origin": _xyz(origin_p),
            "rpy": _xyz(np.zeros(3)),        # axis is specified directly below
            "axis": _xyz(axis_p),
            "lower": lower,
            "upper": upper,
            "effort": eff,
            "velocity": vel,
            "damping": inp.template.damping,
            "friction": inp.template.friction,
        })

    urdf_str = URDF_TEMPLATE.render(
        robot_name=inp.robot_name,
        template_name=inp.template.name,
        links=link_records,
        joints=joint_records,
    )
    urdf_path = output_dir / "robot.urdf"
    urdf_path.write_text(urdf_str)
    return urdf_path
